title: Genomics in the Wild 2024
description: Genomics in the Wild 2024
remote_theme: just-the-docs

url: https://wolfffff.github.io/genomics-in-the-wild-2024

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/wolfffff/genomics-in-the-wild-2024