title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://wolfffff.github.io/genomics-in-the-wild-2024

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/wolfffff/genomics-in-the-wild-2024