jobs: 400
restart-times: 3
max-jobs-per-second: 1
max-status-checks-per-second: 3
cores: 1024
#local-cores: 4
latency-wait: 1200
use-conda: True
keep-going: True
rerun-incomplete: True
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"